# Generated by Django 5.2 on 2025-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for the Module model
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=20)),
                ("is_installed", models.BooleanField(default=False)),
                ("installed_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(max_length=100)),
            ],
        ),
    ]
